import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
df = pd.read_csv('data/processed/contratos_limpios.csv')
os.makedirs('results/figures', exist_ok=True)
fig, ax = plt.subplots(figsize=(10, 6))
df.boxplot(column='monto', by='modalidad', ax=ax, rot=45)
plt.title('Distribucion de Montos por Modalidad')
plt.suptitle('')
plt.ylabel('Monto ($)')
plt.tight_layout()
plt.savefig('results/figures/distribucion_montos.png', dpi=300)
plt.close()
fig, ax = plt.subplots(figsize=(8, 5))
df['estado'].value_counts().plot(kind='bar', ax=ax, color=['#4CAF50', '#2196F3', '#FF5722', '#FFC107'])
plt.title('Numero de Contratos por Estado')
plt.ylabel('Cantidad')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('results/figures/contratos_por_estado.png', dpi=300)
plt.close()
fig, ax = plt.subplots(figsize=(10, 6))
df_risk = df.groupby('entidad')['monto'].sum().sort_values(ascending=False).head(10)
df_risk.plot(kind='barh', ax=ax, color='#E91E63')
plt.title('Top 10 Entidades por Valor Contratado')
plt.xlabel('Monto Total ($)')
plt.tight_layout()
plt.savefig('results/figures/analisis_riesgos.png', dpi=300)
plt.close()
print("3 figuras generadas en results/figures/")
